version '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=app_user
      - MONGO_INITDB_ROOT_PASSWORD=app_password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ~/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - migrations-network

  api:
    container_name: migrations-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3333:3333
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - migrations-network

networks:
  migrations-network:
    driver: bridge
