version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=usr
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=tester
    volumes:
      - ~/mongo:/data/db
    ports:
      - 27017:27017
