name: Test action

on: push

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get migration environment variable uri
        uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.2
        with:
          ssm-path: /dev_api/api_pension/mongo/uri
          prefix: SSM_

      - name: Get migration environment variable first
        uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.2
        with:
          ssm-path: /test/first
          prefix: SSM_

      - name: Setup migration variable
        run: echo I_AM=$SSM_uri >> .env
      - run: echo FIRST=$SSM_first >> .env
      - run: cat .env

      # - name: Set up Node for packages and migrations
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      # - run: npm install
      # - run: npm run test
